### ISSUE TITLE
Braille support in added text

### ISSUE THREAD

**Issue by nwolek** [TimToplak/3DprintedSound#1]
I am exploring the potential for using this project to generate 3D models for blind and low-sighted persons. For that reason, I would like the ability to add text in Braille. I tried the following:

1. pasting in unicode [generated by this website](http://www.byronknoll.com/braille2.html?text=waveform)
2. converting the a [Braille TTF from this site](https://www.tsbvi.edu/download-braille-and-asl-specialty-fonts) using the recommended [Facetype.js website](http://gero3.github.io/facetype.js/)

The first generated some "???" and the second generated the same Braille character over and over.

Can you start by telling me where in the code to look for text handling? Then let me know how we might work together on this. 

Thanks in advance.
-Nathan

**Comment by TimToplak** [comment]
First approach will not work, because the default font doesn't have all the characters defined in default TTF file. For the second approach I think there is a problem in your TTF file. I tried different braille TTF font from this [site](https://www.dafont.com/braille.font), and it seems that is working. 
![image](https://user-images.githubusercontent.com/23419877/85929777-bd23fe00-b8b7-11ea-85cd-899d5cded2f4.png)

**Comment by nwolek** [comment]
Thanks for the reply. Please give me a few days to circle back and confirm.

**Comment by nwolek** [comment]
We've been able to successfully add braille using this method. Just letting you know that it is OK to close the issue.
